# Generated by Django 5.0.6 on 2024-06-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightCancellationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='question',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
