# Generated by Django 5.0.6 on 2024-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightCancellationApp', '0002_pdf_question_alter_pdf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
